CMS/Models/User/UserProfile.cs
using EZGO.Api.Models.Settings;
using EZGO.Api.Models.Users;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models.Action;

namespace WebApp.Models.User
{
    public class UserProfile
    {
        public int Id { get; set; }
        public CompanyModel Company { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string UPN { get; set; }
        public string Picture { get; set; }
        public string Role { get; set; }
        public string Password { get; set; }
        public string PasswordConfirmation { get; set; }
        public string UserName { get; set; }
        public int? SuccessorId { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public bool IsServiceAccount { get; set; }
        public bool? IsTagManager { get; set; }
        public List<AllowedAreaModel> AllowedAreas { get; set; }
        public List<AllowedAreaModel> DisplayAreas { get; set; }
        public ApplicationSettings ApplicationSettings { get; set; }
        public string ValidationKey { get; set; }
        public string UserGUID { get; set; }
        public string SapPmUsername { get; set; }
        public UserExtendedDetails UserExtendedDetails { get; set; }
        public List<EZGO.Api.Models.Enumerations.RoleTypeEnum> Roles {get; set;}
        public UserProfile()
        {
        }

        public UserBasicModel ToBasic()
        {
            return new UserBasicModel
            {
                Id = this.Id,
                Name = string.Format("{0} {1}", FirstName, LastName),
                Picture = Picture
            };
        }
    }
}

CMS/ViewModels/UserPermissionViewModel.cs
using EZGO.Api.Models;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using WebApp.Models.User;

namespace WebApp.ViewModels
{
    public class UserPermissionViewModel : BaseViewModel
    {
        #region - constructor(s) -
        public UserPermissionViewModel()
        {
        }
        #endregion


        #region - -
        public List<Models.User.UserProfile> UserProfiles { get; set; }

        public List<Area> Areas { get; set; }

        public Models.User.UserProfile CurrentUser { get; set; }

        #endregion
    }
}

CMS/ViewModels/UserProfileViewModel.cs
using EZGO.Api.Models;
using EZGO.Api.Models.Users;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models.User;

namespace WebApp.ViewModels
{
    public class UserProfileViewModel : BaseViewModel
    {
        #region - constructor(s) -
        public UserProfileViewModel()
        {
        }

        #endregion
        public List<Area> Areas { get; set; }
        public List<Models.User.UserProfile> UserProfiles { get; set; }
        public Models.User.UserProfile UserProfile { get; set; }
        public UserExtendedDetails UserExtendedDetails { get; set; }
        public bool CurrentUserProfileHasActions { get; set; }
        public Models.User.UserProfile CurrentUser { get; set; }
        public TfaSetup TwoFactorySetup { get; set; }
        public bool EnableRoleManagement { get; set; }
        public bool EnableExtendedUserManagement { get; set; }
    }
}

CMS/Controllers/UserPermissionController.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using EZGO.Api.Models.Settings;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using WebApp.Logic.Interfaces;
using WebApp.Models.User;
using WebApp.ViewModels;
using System.Text.RegularExpressions;
using System.Security.Claims;
using EZGO.Api.Models.Authentication;
using System.Linq;
using System;
using EZGO.Api.Models;
using EZGO.CMS.LIB.Interfaces;
using EZGO.CMS.LIB.Extensions;
using UserProfile = WebApp.Models.User.UserProfile;
using System.Net;
using System.IO;
using System.Net.Http;
using System.Net.Http.Headers;
using WebApp.Models;
using System.Text;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using EZGO.Api.Models.Users;
using Amazon;

/// <summary>
/// ENTIRE PAGE AND STRUCTURE MUST BE REFACTORED
/// -> individual calls must be based on individual API calls not on collection calls and manually filtering on Id
/// -> not on all routes all data must be retrieved. Currently more it less it does. 
/// -> All double not user functionality and or views must be merged or removed so it works properly. 
/// -> All routes and views must have a full route in attribute and full location to view within the method!
/// </summary>
/// 
namespace WebApp.Controllers
{
    public class UserPermissionController : BaseController
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IApiConnector _connector;
        private readonly string _apiBaseUrl;

        public UserPermissionController(ILogger<HomeController> logger, IApiConnector connector, ILanguageService language, IHttpContextAccessor httpContextAccessor, IConfigurationHelper configurationHelper, IApplicationSettingsHelper applicationSettingsHelper, IInboxService inboxService) : base(language, configurationHelper, httpContextAccessor, applicationSettingsHelper, inboxService)
        {
            _logger = logger;
            _connector = connector;
            _apiBaseUrl = configurationHelper.GetValueAsString("AppSettings:ApiUri");
        }

        // GET: UserPermission
        public async Task<ActionResult> Index()
        {
            var output = new UserPermissionViewModel();
            output.ApplicationSettings = await this.GetApplicationSettings();

            if (!((User.IsInRole("serviceaccount") || ((output.ApplicationSettings?.Features?.RoleManagementEnabled.HasValue == false || output.ApplicationSettings?.Features?.RoleManagementEnabled.Value == false) && User.IsInRole("manager")) || (output.ApplicationSettings?.Features?.RoleManagementEnabled.HasValue == true && output.ApplicationSettings?.Features?.RoleManagementEnabled.Value == true && User.IsInRole("usermanager")))))
            {
                return NoContent(); //no rights to part of site so return no content;
            }

            output.NewInboxItemsCount = await GetInboxCount();
            output.Locale = _locale;
            output.CmsLanguage = await _language.GetLanguageDictionaryAsync(_locale);
            output.Filter.Module = FilterViewModel.ApplicationModules.USERS;
            output.Filter.CmsLanguage = output.CmsLanguage;
            output.PageTitle = "User overview";

            // current user
            output.CurrentUser = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.UserData)?.Value.ToObjectFromJson<UserProfile>();

            var arearesult = await _connector.GetCall(Logic.Constants.Task.GetTaskAreas);
            if (arearesult.StatusCode == System.Net.HttpStatusCode.OK)
            {
                output.Areas = JsonConvert.DeserializeObject<List<Area>>(arearesult.Message);
            }

            var result = await _connector.GetCall(Logic.Constants.User.UserPermissionUrl);
            if (result.StatusCode == System.Net.HttpStatusCode.OK)
            {
                output.UserProfiles = JsonConvert.DeserializeObject<List<UserProfile>>(result.Message);
            }

            return View(output);
        }

        [HttpPost]
        public async Task<ActionResult> LoadData()
        {
            //weird method??
            var model = new UserPermissionViewModel();
            model.NewInboxItemsCount = await GetInboxCount();
            model.Filter.Module = FilterViewModel.ApplicationModules.USERS;
            model.Locale = _locale;
            model.PageTitle = "User overview";
            model.CurrentUser = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.UserData)?.Value.ToObjectFromJson<UserProfile>();
            model.CmsLanguage = await _language.GetLanguageDictionaryAsync(_locale);

            var result = await _connector.GetCall(Logic.Constants.User.UserPermissionUrl);
            if (result.StatusCode == System.Net.HttpStatusCode.OK)
            {
                model.UserProfiles = JsonConvert.DeserializeObject<List<UserProfile>>(result.Message);
            }

            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();

                // Skip number of Rows count
                var start = Request.Form["start"].FirstOrDefault();

                // Paging Length 10,20
                var length = Request.Form["length"].FirstOrDefault();

                // Sort Column Name
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();

                // Sort Column Direction (asc, desc)
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();

                // Search Value from (Search box)
                var searchValue = Request.Form["search[value]"].FirstOrDefault();

                //Paging Size (10, 20, 50,100)
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;

                // getting all Customer data
                var users = (from user in model.UserProfiles
                             select user);
                //Sorting
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {
                    // users = users.OrderBy(sortColumn + " " + sortColumnDirection);
                }

                //Search
                if (!string.IsNullOrEmpty(searchValue))
                {
                    users = users.Where(m => m.FirstName == searchValue || m.LastName == searchValue || m.Role == searchValue);
                }

                //total number of rows counts
                recordsTotal = users.Count();
                //Paging
                var data = users.Skip(skip).Take(pageSize).ToList();
                //Returning Json Data
                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
            }
            catch (Exception)
            {
                throw;
            }
        }

        #region - user profile details -
        // GET: UserPermission/Details/5
        public async Task<ActionResult> Details(int id)
        {
            UserProfileViewModel output = new UserProfileViewModel();
            output.ApplicationSettings = await this.GetApplicationSettings();

            if (!((User.IsInRole("serviceaccount") || ((output.ApplicationSettings?.Features?.RoleManagementEnabled.HasValue == false || output.ApplicationSettings?.Features?.RoleManagementEnabled.Value == false) && User.IsInRole("manager")) || (output.ApplicationSettings?.Features?.RoleManagementEnabled.HasValue == true && output.ApplicationSettings?.Features?.RoleManagementEnabled.Value == true && User.IsInRole("usermanager")))))
            {
                return NoContent(); //no rights to part of site so return no content;
            }

            output.NewInboxItemsCount = await GetInboxCount();
            output.CurrentUser = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.UserData)?.Value.ToObjectFromJson<UserProfile>();
            output.CmsLanguage = await _language.GetLanguageDictionaryAsync(_locale);
            output.Filter.Module = FilterViewModel.ApplicationModules.USERS;
            output.Locale = _locale;
            output.EnablingAuditing = output.ApplicationSettings?.Features?.AuditTrailDetailsEnabled == true && User.IsInRole("manager");

            //set specific boolean for display changes (show/not show certain parts.
            if (output.ApplicationSettings?.Features?.RoleManagementEnabled.HasValue == true && output.ApplicationSettings?.Features?.RoleManagementEnabled == true && (User.IsInRole("serviceaccount") || User.IsInRole("rolemanager")))
            {
                output.EnableRoleManagement = true;
            }

            if (output.ApplicationSettings?.Features?.UserExtendedDetailsEnabled.HasValue == true && output.ApplicationSettings?.Features?.UserExtendedDetailsEnabled.Value == true)
            {
                output.EnableExtendedUserManagement = true;
            }

            //getting areas
            var arearesult = await _connector.GetCall(Logic.Constants.Task.GetTaskAreas);
            if (arearesult.StatusCode == System.Net.HttpStatusCode.OK)
            {
                output.Areas = JsonConvert.DeserializeObject<List<Area>>(arearesult.Message);
            }

            if (id > 0)
            {
                string uri = string.Format(output.EnableRoleManagement ? string.Concat(Logic.Constants.User.UserProfileUrl, ",roles") : Logic.Constants.User.UserProfileUrl, id.ToString());
                var result = await _connector.GetCall(uri);
                if (result.StatusCode == System.Net.HttpStatusCode.OK)
                {

CMS/Views/UserPermission/Index.cshtml
@model WebApp.ViewModels.UserPermissionViewModel
@using WebApp.Models.User
@{
    Layout = "_Layout_template";
    ViewData["Title"] = Model?.CmsLanguage?.GetValue(LanguageKeys.User.OverviewTitle, "Users overview") ?? "Users overview";
}

@section CSS{

    <style>
        .userprofile {
            transition: transform .2s; /* Animation */
        }

            .userprofile:hover {
                border: solid 1px #93c54b;
                box-shadow: 0 .425rem .75rem rgba(0,0,0,.075) !important;
                color: #93c54b !important;
                transform: scale(1.02);
            }
    </style>

}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-0">
            <div class="col-sm-6">
                &nbsp;
                <h1>@(Model?.CmsLanguage?.GetValue(LanguageKeys.User.OverviewTitle, "Users overview") ?? "Users overview")</h1>
            </div>
            <div class="col-sm-6 d-flex  flex-row-reverse">
                <a asp-controller="UserPermission" asp-action="Details" class="btn btn-ezgo btn-sm mr-2 shadow-sm mt-auto">@(Model?.CmsLanguage?.GetValue(LanguageKeys.User.ButtonAddUser, "Add User") ?? "Add User") </a>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">

    <div class="container-fluid">

        <div class="row pt-1" style="height:calc(100vh - 165px);">

            <div class="col-xl-3 d-none d-xl-inline-block" style="padding-right: 15px">
                <div class="card card-filter h-100">
                    <div class="card-header pb-0 d-flex" style="border-bottom: none;width:100%">
                        <h3 class="card-title d-flex" style="width:100%">@(Model?.CmsLanguage?.GetValue(LanguageKeys.Filters.CardTitle, "Filters") ?? "Filters")</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <div class="input-group-append">
                                    <button type="button" class="btn" onclick="resetFilters()" title="@(Model?.CmsLanguage?.GetValue(LanguageKeys.Filters.ResetHover, "Reset filters") ?? "Reset filters")"><i class="fas fa-undo"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body pt-0">
                        <partial name="_filters_block" model="Model.Filter" />
                    </div>
                </div>
            </div>


            <div class="col-lg-12 col-xl-9" style="padding-left: 7.5px">
                <div class="card mb-1" style="margin-left: 0px">
                    <div class="card-header d-flex" style="margin-left:-11px; height: 55px">
                        <div style="display: flex; height: 100%; width: 100%; align-items: center">
                            <h3 class="card-title d-sm-inline-block">
                                @(Model?.CmsLanguage?.GetValue(LanguageKeys.User.OverviewListTitle, "Users") ?? "Users") <span id="counter"></span>
                            </h3>
                        </div>
                        <div style="width: auto; text-align: right">
                            <div class="card-tools" style="width: 236px; display: inline-block">
                                <div class="input-group input-group-sm">
                                    <input type="text" placeholder="@(Model?.CmsLanguage?.GetValue(LanguageKeys.User.ListSearchTitle, "Search") ?? "Search")" class="form-control float-right" id="searchField">

                                    <div class="input-group-append">
                                        <button type="button" class="btn btn-default d-block d-xl-none" data-bs-toggle="collapse" data-bs-target=".collapseFilter"><i class="fas fa-filter"></i></button>
                                        <button type="button" class="btn btn-default d-xl-none" onclick="resetFilters()" title="@(Model?.CmsLanguage?.GetValue(LanguageKeys.Filters.ResetHover, "Reset filters") ?? "Reset filters")" data-action="resetfilters"><i class="fas fa-undo"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="d-xl-none" style="padding-left: 5px; padding-right: 5px">
                        <div class="card-header collapse collapseFilter px-0">
                            <partial name="_filters_inline" model="Model.Filter" />
                        </div>
                    </div>

                </div>

                <div id="contentCol" class="row card-deck align-content-start" style="height: calc(100vh - 235px);overflow:auto;padding-top:6px;">
                    @{
                        var userProfiles = Model.UserProfiles;
                        @if (!Model.CurrentUser.IsServiceAccount)
                        {
                            userProfiles = Model.UserProfiles.Where(p => !p.IsServiceAccount).ToList();
                        }
                    }

                    @foreach (UserProfile profile in userProfiles)
                    {
                        var picture = WebApp.Helpers.MediaHelpers.GetMediaImageUrl(Model.ApplicationSettings, profile.Picture);

                        <div class="col-lg-3 col-md-4 col-sm-12 p-0 pb-3 results" data-role="@profile.Role">

                            <div class="card userprofile" data-containertype="user_container" data-role="@profile.Role" data-id="@profile.Id" style="cursor:pointer;min-height:250px;">
                                <div class="body">
                                    <div class="cp_img text-center mt-3">
                                        <img src="/images/media-loading.gif" data-src="@picture" alt="Product" class="img-fluid rounded-circle" loading="lazy" style="width: 125px;height: 125px;object-fit: cover;object-position: center;">
                                    </div>
                                    <div class="product_details text-center mt-3">
                                        <h5>@profile.FirstName @profile.LastName</h5>
                                        <ul class="product_price list-unstyled">
                                            <li>@profile.Role.Replace('_', ' ')</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                        </div>

                    }

                </div>
            </div>
        </div>
    </div>
</section>

<div id="area_full_container" style="display:none">
    <partial name="_area_list" model="Model.Areas" />
</div>

@section Scripts {

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="/js/areafilter.js"></script>
    <script>
        $(document).ready(function () {
            ezgomediafetcher.preloadVisibleImagesAndVideos();
            var cntr = $('#contentCol .card:visible').length;
            $('#counter').html('&nbsp;(' + cntr + ')');

            var filters = localStorage.getItem('userfilters');
            if (filters !== null) {
                var filtersJson = JSON.parse(filters);
                filterObj = filtersJson;
                //apply filters
                $('#roleFilter').val(filterObj.role).trigger('change');
                $('#roleFilterInline').val(filterObj.role).trigger('change');;
                //scroll to scrollYPosition
                $('#contentBody').scrollTop(filterObj.scrollYPosition);
                var arr = $('#roleFilter').val();
                if (arr !== undefined) {
                    var roles = arr.join(",");
                }
                filter(roles);
                var cntr = $('#contentCol .card:visible').length;
                $('#counter').html('&nbsp;(' + cntr + ')');
                $('.bootstrap-select button .filter-option').addClass('d-flex');
                ezgomediafetcher.preloadVisibleImagesAndVideos();
            }

            $("#searchField").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#contentCol div.userprofile").filter(function () {
                    $(this).parent('div').toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
                var cntr = $('#contentCol .card:visible').length;
                $('#counter').html('&nbsp;(' + cntr + ')');
                ezgomediafetcher.preloadVisibleImagesAndVideos();
            });

            $('[data-containertype="user_container"]').on('click', function () {
                $('.userRow').css('backgroundColor', '');
                $(this).css('backgroundColor', '#fff');
                document.location.href = '/userpermission/details/' + $(this).data('id');
            });

            $('#btn-close').on('click', function (e) {
                $('.userRow').css('backgroundColor', '');
                $('.panel-wrap').css('transform', 'translateX(100%)');
            });

            $('#myModal').on('shown.bs.modal', function () {
                $('#myInput').focus()
            });

            $('[data-role="roleFilterInline"]').on('change', function (e, clickedIndex, isSelected, previousValue) {
                $(`#roleFilter`).val($(`#roleFilterInline`).val()).trigger('change');

                $(`#roleFilter`).trigger('change');
            });

            $('[data-role="roleFilter"]').on('change', function (e, clickedIndex, isSelected, previousValue) {

                var arr = $('#roleFilter').val();
                if (arr !== undefined) {
                    var roles = arr.join(",");
                }
                filterObj.role = arr;

                localStorage.setItem('userfilters', JSON.stringify(filterObj));

                $(`#roleFilterInline`).val($(`#roleFilter`).val()).trigger('change');
                filter(roles);
                var cntr = $('#contentCol .card:visible').length;
                $('#counter').html('&nbsp;(' + cntr + ')');
                $('.bootstrap-select button .filter-option').addClass('d-flex');
                ezgomediafetcher.preloadVisibleImagesAndVideos();
            });

            $("#contentCol").on('filterDone', function () {
                var cntr = $('#contentCol .card:visible').length;
                $('#counter').html('&nbsp;(' + cntr + ')');
            });

            $('.bootstrap-select button .filter-option').addClass('d-flex');
        });

        function resetFilters() {
            $("#roleFilter").val('default').trigger('change');
            $("#roleFilterInline").val('default').trigger('change');

            $('#searchField').val('');

            filterObj.role = "";

            localStorage.setItem('userfilters', JSON.stringify(filterObj));
            $("#contentCol div.results").show();
            var cntr = $('#contentCol .card:visible').length;
            $('#counter').html('&nbsp;(' + cntr + ')');
            $('.bootstrap-select button .filter-option').addClass('d-flex');
        }

        function filter(value) {
            if (!value) {
                $("#contentCol div.results").show();
                return;
            }
            $("#contentCol div.results").hide();
            if (value) {
                var roles = String(value).split(',');
                $(roles).each(function (index, role) {
                    //console.log('role: ' + role);
                    $("#contentCol div.results").each(function (index, item) {
                        var card = $(item);
                        var inRole = card.data('role') === role;
                        //console.log(index + ' -> ' + card.data('role') + ' -> inrole: ' + inRole);
                        if (inRole) {
                            var id = card.data('id')
                            card.show();
                        }
                    });

                });
            }
        }
    </script>
    <script>
        $('#contentCol').on('scroll', function () {
            ezgomediafetcher.preloadVisibleImagesAndVideos();

        });

        var filterObj = {
            role: ""
        }
    </script>
}

CMS/Views/UserPermission/_area_item.cshtml
@{
    <div id="area_container">
        @foreach (var area in Model)
        {
            @area.Name
            <br />

        }
    </div>
}

CMS/Views/UserPermission/_area_list.cshtml
@model List<EZGO.Api.Models.Area>


<div data-containertype="area_choice_list" style="">
    <ul style="@(Model.FirstOrDefault()?.Level == 0 ? "padding-left:0": "")">
        @foreach (var area in Model)
        {
            <li data-id="@area.Id" data-name="@area.Name" data-fullname="@area.FullDisplayName" data-parent="@area.ParentId" data-containertype="area_choice" data-level="@area.Level" style="@(area.Level == 0 ? "display:inline;margin-left:0px;font-size:16px;": "font-size:14px;")" title="@area.FullDisplayName">
                <div class="area-title" style="border-bottom: 1px solid #C0C0C0;position:relative"><div style="padding:5px;" data-containertype="title" class="fle">@area.Name</div><span style="position:absolute; top:4px; right:5px;font-size:14px;display:none;" data-buttontype="deselect" title="Remove @area.Name">x</span></div>
                @{
                    if (area.Children != null && area.Children.Count > 0)
                    {

                        <partial name="_area_list" model="@area.Children" />

                    }
                }
            </li>

        }
    </ul>
</div>